services:
  db:
    image: postgres:15
    container_name: gas_library_hub_db
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - gas_library_hub_db_data:/var/lib/postgresql/data

volumes:
  gas_library_hub_db_data:
